

JASPER_ACQUIRE_SUBSCRIBE = 'JASPER_ACQUIRE'
JASPER_SYNC_CARD_SUBSCRIBE = 'JASPER_SYNC_CARD'
JASPER_QUERY_LIMIT = 1000

CMPP_ACQUIRE_SUBSCRIBE = 'CMPP_ACQUIRE'
CMPP_SYNC_CARD_SUBSCRIBE = 'CMPP_SYNC_CARD'
